services:
  ftso-mysql:
    image: "mysql"
    restart: "always"
    container_name: "flare-ftso-mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - 3306:3306
    volumes:
      - ./db_init/:/docker-entrypoint-initdb.d/
